<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Correct URL and port -->
		<DevServerPort>5173</DevServerPort>
		<DevServerUrl>http://0.0.0.0:5173/</DevServerUrl>
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.14" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.14" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EpicPetEMR.Shared\EpicPetEMR.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\NewFolder" />
		<Folder Include="wwwroot\NewFolder1\" />
	</ItemGroup>

</Project>